# Generated by Django 5.2.17 on 2026-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500, unique=True)),
                ('ville', models.CharField(max_length=120)),
                ('secteur', models.CharField(max_length=80)),
                ('contact', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
