# Generated by Django 5.2.17 on 2026-09-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': "Tuteur d'entreprise",
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500, unique=True)),
                ('ville', models.CharField(max_length=120)),
                ('secteur', models.CharField(max_length=80)),
                ('contact', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(upload_to='')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='stages.tuteurentreprise')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'ordering': ['nom'],
            },
        ),
    ]
