# Generated by Django 5.2.17 on 2026-09-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField()),
            ],
            options={
                'verbose_name': 'Competence',
            },
        ),
        migrations.CreateModel(
            name='EnseignantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('departement_pedagogique', models.CharField()),
            ],
            options={
                'verbose_name': 'Enseignant de reference',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField()),
                ('promotion', models.CharField()),
                ('competence', models.ManyToManyField(related_name='etudiants', to='stages.competence')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField()),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_stagiaires', models.IntegerField()),
                ('competence', models.ManyToManyField(related_name='offres', to='stages.competence')),
            ],
            options={
                'verbose_name': 'Offre de stage',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidate', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidature', to='stages.etudiant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['date_candidate'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(null=True)),
                ('enseignants', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.enseignantreference')),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.entreprise')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='stages.etudiant')),
                ('tuteur', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stage', to='stages.tuteurentreprise')),
            ],
            options={
                'verbose_name': 'Stage',
                'ordering': ['date_debut'],
            },
        ),
    ]
